#!/usr/bin/env node
import { access, copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { execFileSync } from "node:child_process";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

function reportFatal(error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
process.on("uncaughtException", reportFatal);
process.on("unhandledRejection", reportFatal);

function usage() {
  console.error(`Usage: install-adapter.mjs [options]\n\nInstalls and configures the pi-foundry adapter in the current user Pi agent repo.\nNo azd template is required; the skill owns the adapter bundle.\n\nOptions:\n  --environment <name>       Optional azd environment name to select/create.\n  --agent-name <name>        Foundry Hosted Agent name. Defaults to sanitized repo directory name.\n  --display-name <name>      Display name. Defaults from agent name.\n  --runtime-image <image>\n  --cpu <value>\n  --memory <value>\n  --model <model>\n  --artifact-mode <disabled|static-web>\n  --yes                     Reserved for skill confirmation flows; currently non-interactive.\n  --replace-azure          Replace an existing non-pi-foundry azure.yaml after backing it up.\n  --replace-agent          Replace existing non-pi-foundry root agent.yaml/agent.manifest.yaml after backing them up.\n  --doctor                  Run adapter doctor after render. Requires azd env values.\n`);
}

function parseArgs(argv) {
  const values = { doctor: false };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--help" || arg === "-h") {
      usage();
      process.exit(0);
    }
    if (arg === "--yes") {
      values.yes = true;
      continue;
    }
    if (arg === "--doctor") {
      values.doctor = true;
      continue;
    }
    if (arg === "--replace-azure") {
      values.replaceAzure = true;
      continue;
    }
    if (arg === "--replace-agent") {
      values.replaceAgent = true;
      continue;
    }
    if (!arg.startsWith("--")) throw new Error(`Unexpected argument: ${arg}`);
    const value = argv[index + 1];
    if (!value || value.startsWith("--")) throw new Error(`Missing value for ${arg}`);
    values[arg.slice(2)] = value;
    index += 1;
  }
  return values;
}

async function exists(path) {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function run(command, args, options = {}) {
  return execFileSync(command, args, {
    encoding: "utf8",
    stdio: options.quiet ? ["ignore", "pipe", "pipe"] : "inherit",
    timeout: options.timeout ?? 300000,
    env: process.env,
  })?.trim();
}

function tryRun(command, args) {
  try {
    return run(command, args, { quiet: true });
  } catch {
    return undefined;
  }
}

function sanitizeAgentName(value) {
  const words = value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
  return words || "pi-agent";
}

function displayNameFromAgentName(value) {
  return value.split("-").filter(Boolean).map((word) => word[0]?.toUpperCase() + word.slice(1)).join(" ") || "Pi Agent";
}

async function copyAdapterFile(source, target) {
  await mkdir(dirname(target), { recursive: true });
  const next = await readFile(source, "utf8");
  const current = (await exists(target)) ? await readFile(target, "utf8") : undefined;
  if (current === next) {
    console.log(`unchanged ${target}`);
    return;
  }
  await copyFile(source, target);
  console.log(`${current === undefined ? "created" : "updated"} ${target}`);
}

async function installAdapterBundle(assetDir) {
  for (const file of ["README.md", "render.mjs", "doctor.mjs", "postdeploy.mjs"]) {
    await copyAdapterFile(join(assetDir, file), `.azd/pi-foundry/${file}`);
  }
}

function isPiFoundryManagedAzure(text) {
  if (text.includes("Generated by pi-foundry") || text.includes("pi-foundry bootstrap azd file") || text.includes(".azd/pi-foundry/pi-foundry.yaml")) return true;
  return /host:\s*azure\.ai\.agent/.test(text)
    && /\.azd\/pi-foundry\/Dockerfile/.test(text)
    && /\.azd\/pi-foundry\/render\.mjs/.test(text)
    && /\.azd\/pi-foundry\/doctor\.mjs/.test(text)
    && /\.azd\/pi-foundry\/postdeploy\.mjs/.test(text);
}

function isPiFoundryGeneratedFile(text) {
  return text.includes("Generated by pi-foundry") && text.includes(".azd/pi-foundry/pi-foundry.yaml");
}

async function guardAzureYaml({ replaceAzure }) {
  if (!(await exists("azure.yaml"))) return;
  const existing = await readFile("azure.yaml", "utf8");
  if (isPiFoundryManagedAzure(existing)) return;
  if (!replaceAzure) {
    throw new Error("azure.yaml already exists and is not pi-foundry-managed. Re-run after user confirmation with --replace-azure, or manually merge pi-foundry azd settings.");
  }
  const backup = `azure.yaml.bak.${new Date().toISOString().replace(/[:.]/g, "-")}`;
  await writeFile(backup, existing);
  process.env.PI_FOUNDRY_ALLOW_AZURE_OVERWRITE = "1";
  console.log(`backed up existing azure.yaml to ${backup}`);
}

async function guardRootAgentFiles({ replaceAgent }) {
  for (const file of ["agent.yaml", "agent.manifest.yaml"]) {
    if (!(await exists(file))) continue;
    const existing = await readFile(file, "utf8");
    if (isPiFoundryGeneratedFile(existing)) continue;
    if (!replaceAgent) {
      throw new Error(`${file} already exists and is not pi-foundry-generated. Re-run after user confirmation with --replace-agent, or manually merge pi-foundry agent settings.`);
    }
    const backup = `${file}.bak.${new Date().toISOString().replace(/[:.]/g, "-")}`;
    await writeFile(backup, existing);
    process.env.PI_FOUNDRY_ALLOW_AGENT_OVERWRITE = "1";
    console.log(`backed up existing ${file} to ${backup}`);
  }
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const assetDir = join(scriptDir, "../assets/adapter");
const args = parseArgs(process.argv.slice(2));

if (await exists("Dockerfile.runtime") && await exists(".agents/skills/pi-foundry")) {
  throw new Error("Current directory looks like the pi-foundry development checkout. Run install from the user's existing Pi agent repo.");
}

await guardAzureYaml({ replaceAzure: args.replaceAzure });
await guardRootAgentFiles({ replaceAgent: args.replaceAgent });
await mkdir(".azd/pi-foundry", { recursive: true });
await installAdapterBundle(assetDir);
run("node", [join(scriptDir, "merge-dockerignore.mjs")]);

const agentName = sanitizeAgentName(args["agent-name"] ?? basename(process.cwd()));
const displayName = args["display-name"] ?? displayNameFromAgentName(agentName);
const updateArgs = [join(scriptDir, "update-config.mjs"), "--agent-name", agentName, "--display-name", displayName];
for (const [option, flag] of [
  ["runtime-image", "--runtime-image"],
  ["cpu", "--cpu"],
  ["memory", "--memory"],
  ["model", "--model"],
  ["artifact-mode", "--artifact-mode"],
]) {
  if (args[option]) updateArgs.push(flag, args[option]);
}
run("node", updateArgs);
run("node", [".azd/pi-foundry/render.mjs", "--check"]);

if (args.environment) {
  if (tryRun("azd", ["env", "select", args.environment]) === undefined) run("azd", ["env", "new", args.environment]);
}

if (args.doctor) run("node", [".azd/pi-foundry/doctor.mjs"]);
else console.log("pi-foundry adapter installed. Configure azd env values, then run: node .azd/pi-foundry/doctor.mjs && azd up");
